### ISSUE TITLE
Custom UA

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#114]

**Comment by sammacbeth** [comment]
As of build `2020-09-11` the UA is:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Ghostery/2020.9`

Should we also include a `Firefox/$VERSION` string in there too so we get featured detected properly as Firefox for webcompat issues?

**Comment by sammacbeth** [comment]
We can set the `general.useragent.compatMode.firefox` to true, which adds a Firefox compat string to the UA (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox). This would change the UA to `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:80.0) Gecko/20100101 Firefox/80.0 Ghostery/2020.9`

**Comment by chrmod** [comment]
@sammacbeth that would be perfect

**Comment by sammacbeth** [comment]
We've had a few reports of issues caused by our custom UA:
 * `web.whatsapp.com` - says browser is out of date
 * 1. accessing https://get2.adobe.com/reader/ then 2. clicking " Download Adobe Acrobat Pro Trial" - gives a 404

We can do:
 * Per site UA overrides
 * Revert to Firefox UA string (either via `general.useragent.override` pref, or via code modification).
 * Move Ghostery part of UA string to make break less things (i.e. mimic Ghostery android UA pattern).

Any UA changes will break extension browser detection, which was written for the current UA format. We would have to update that code before making a change here.
