### ISSUE TITLE
Find out best way to change prefs on update

### ISSUE THREAD

**Issue by chrmod** [ghostery/user-agent-desktop#199]

**Comment by sammacbeth** [comment]
I investigated this, and found that `firefox-branding.js` *is* evaluated on every start. When running from a local build there is a parse error due to the missing semicolon here: https://github.com/ghostery/user-agent-desktop/blob/fa94d2f289f6497fe405f6f6f57f4f1a559f986a/branding/ghostery/pref/firefox-branding.js#L104

I'll make a PR fixing this issue.

**Comment by chrmod** [comment]
Let's do some local testing and if it's fine just close this issue.

**Comment by chrmod** [comment]
Looks like all if fine if the prefs file are correctly formatted
