### ISSUE TITLE
Logo File on Install Prompt

### ISSUE THREAD

**Issue by tillhouse** [ghostery/user-agent-desktop#349]
The logo file on the install prompts does not seem to be high-resolution and instead looks fuzzy.  See the screenshots below:
![image](https://user-images.githubusercontent.com/1709237/99088491-1f954680-259a-11eb-8c0f-a08a0091444b.png)
![image](https://user-images.githubusercontent.com/1709237/99088509-23c16400-259a-11eb-891a-dd79632c5d36.png)

**ACCEPTANCE CRITERIA:**
* Use the attached logo icon for these prompts.

**DESIGN SPECS & ASSETS:** 
[ghosty_cBk_icon.zip](https://github.com/ghostery/user-agent-desktop/files/5537682/ghosty_cBk_icon.zip)

**Comment by sammacbeth** [comment]
The file in the second image is this one: https://raw.githubusercontent.com/ghostery/user-agent-desktop/master/brands/ghostery/branding/wizHeader.bmp

I'm not sure if it's possible to use a higher definition one, and the issue seems to be tied to hi-dpi displays, as this is just a simple bitmap. Firefox don't use this installer, so I guess haven't invested in a hi-dpi solution for this - their version of the file is the same resolution: https://searchfox.org/mozilla-central/source/browser/branding/official/wizHeader.bmp
