### ISSUE TITLE
Make this comparable with extensions from the Chrome web store

### ISSUE THREAD

**Issue by 2br-2b** [ghostery/user-agent-desktop#388]
Since lots of the WebExtensions in the Chrome Web Store are already compatible with Ghostery, could we use a Chromium user agent when visiting the site and make the extensions found there installable on Ghostery?

**Comment by chrmod** [comment]
Ghostery Destkop Browser is based on Mozilla Firefox, so Chrome Web Store addons wont work. Please check [AMO](https://addons.mozilla.org/en-US/firefox/) for Ghostery Browser compatible addons.

**Comment by 2br-2b** [comment]
Yes, but since Firefox and Chromium both use many of the same WebExtension APIs, I would think many (if not most) extensions found there would also work on Firefox/GhosteryCA%2!*P6yWCBvKPpvXbLN

**Comment by chrmod** [comment]
Unfortunately that cannot work for variety of reasons, to list a few:
* extensions are code signed for a given platform
* there are differences in manifests
* some extension have differences between the platforms due to API differences 
* Firefox does not handle .crx format, so it is not only UA that require a change

**Comment by 2br-2b** [comment]
Okay. Thanks!

I think this could be a cool feature, but I see why it isn't supported.
