### ISSUE TITLE
Configure default top sites

### ISSUE THREAD

**Issue by sammacbeth** [ghostery/user-agent-desktop#410]
On a new profile default top sites are seeded from Firefox's settings service. We should consider removing these, or manually selecting initial top sites.

<img width="705" alt="Screenshot 2020-12-11 at 14 55 45" src="https://user-images.githubusercontent.com/248111/101911813-2dea7880-3bc1-11eb-9efd-db99b32fdb36.png">

**Comment by 2br-2b** [comment]
Some websites that could be good default sites are:
- [Ghostery.com](https://www.ghostery.com/) - for obvious reasons
- [Whotracks.me](https://whotracks.me/) - though the most recent report is still from 2018, it's still up-to-date and it has lots of good info. It's also a Ghostery project, so it'd be fitting to link to it in the browser
- [Privacytools.io](https://privacytools.io/) - a good website with tools for maintaining your privacy
- [AlternativeTo](https://alternativeto.net/) - a good website for finding privacy-respecting alternatives to many websites
- [AMO](https://addons.mozilla.com/) - give the users the option to customize their browser right out of the gate
- [Jitsi Meet](https://meet.jit.si/) - a private video calling website

Having Youtube, Facebook, and Amazon linked would be helpful for users, but since these websites don't necessarily respect user privacy, it may be best not to include them.

**Comment by chrmod** [comment]
Promoting this issue for implementation for public release.

@2br-2b thanks for the proposition!

**Comment by chrmod** [comment]
Lets put the following:

https://www.ghostery.com/who
https://whotracks.me/
https://privacytools.io/
https://alternativeto.net/
https://addons.mozilla.org

**Comment by 2br-2b** [comment]
https://www.ghostery.com/who talks about Cliqz, who is no longer in operation. Will this page be updated?

It may be better to do https://www.ghostery.com/about-ghostery/, which talks about who Ghostery is, rather than Cliqz.

**Comment by chrmod** [comment]
Make sense, thanks for suggestion!
