### ISSUE TITLE
Add fallback in case new tab page doesn't load

### ISSUE THREAD

**Issue by 2br-2b** [ghostery/user-agent-desktop#468]
On my laptop, the new tab page (https://glowstery.com/) won't load for some reason. It works fine on my phone, so it's not a firewall issue. It's also not a browser-specific issue, as the page also doesn't work on Brave, a Chromium-based browser.

Regardless, that isn't the reason I'm opening this issue.

I'm opening the issue because, when I can't load the page, the "Secure Connection Failed" page loads, which just looks bad when this comes up on every new tab:

![screenshot](https://user-images.githubusercontent.com/43968991/106301878-40c71400-6226-11eb-8de9-7b740430b2f9.png)

There should be an alternative page that loads when some error connecting to glowstery.com comes up - that way, users don't keep getting greeted by this page.

**Comment by chrmod** [comment]
Thank you for the report. 

We've tried to use ghosterysearch.com as a new tab page but it was quite problematic. Since https://github.com/ghostery/user-agent-desktop/commit/dea3688bf312f6effb0c9b1459122b3f8da7a7d2 the new tab page is now an independent system addon so will work offline perfectly well.

**Comment by 2br-2b** [comment]
Thanks for the update!

In that case, should that also close #469, or is that a separate implementation?
