### ISSUE TITLE
Arkenfox user.js

### ISSUE THREAD

**Issue by 2br-2b** [ghostery/user-agent-desktop#486]
I don't know how many of the options here are already covered by Betterfox, but [Arkenfox](https://github.com/arkenfox/user.js) seems to have some good default about:config preferences.

I can go over these options and help to merge them, but it may be best to wait until [BetterFox's changes](https://github.com/ghostery/user-agent-desktop/pull/484/) are finalized to avoid repetition/conflict of options.

**Comment by yokoffing** [comment]
> Arkenfox seems to have some good default about:config preferences.

### Differences

Arkenfox/ghacks are an amazing team. They are a cornerstone for most people's `user.js` file. I use them as a source for BetterFox. However, please note we have two different philosophies and audiences:

Arkenfox/ghacks user.js utilizes `privacy.firstparty.isolate` (FPI) and `privacy.resistFingerprinting` (RF) to guide their decision-making for prefs. They use the philosophy behind TOR (make all users look the same) to protect against fingerprinting (both first- and third-party). You cannot enable these preferences without many [annoyances/breakages](https://www.reddit.com/r/firefox/comments/kz65qm/aboutconfig_hardening/gjn4cai?utm_source=share&utm_medium=web2x&context=3) in common browsing use cases. Arkenfox's user base has a high tolerance for breakage related to niche privacy concerns.

BetterFox uses [Dynamic First Party Isolation](https://github.com/yokoffing/Better-Fox/blob/9856e103272a97f363e24042be4b90dbf4a13628/SecureFox.js#L64-L71) (dFPI) to protect against third-party tracking. The Betterfox user.js does not offer browser-level protection against fingerprintering except enforcing the Disconnect list native to Firefox's Enhanced Tracking Protection (ETP) to block them when detected (`privacy.trackingprotection.fingerprinting.enabled`). This is to prevent breakage and keep your browser useable.

BetterFox is targeted for mainstream, everyday users and workflows. "Provide privacy, but not at the cost of functionality." All of this is stated in the [readme](https://github.com/yokoffing/Better-Fox#aboutprivacy). (If your threat level calls for anonymity and not just reasonable privacy, you should use TOR.) So BetterFox does not protect users from fingerprinting specifically outside of what's offered with ETP and some things like disabling the [Battery API, click tracking, etc](https://github.com/yokoffing/Better-Fox/blob/9856e103272a97f363e24042be4b90dbf4a13628/user.js#L56-L59).

### Are extensions useful against fingerprinting?

Extensions are limited. I agree with Arkenfox [here](https://github.com/arkenfox/user.js/wiki/4.1-Extensions#small_orange_diamond-%EF%B8%8F-anti-fingerprinting-extensions-fk-no) that extensions made solely for anti-fingerprinting are not worth using.

uBlock Origin (depending on what filter lists you use) can block _known_ fingerprinters (and trackers in general) but not those _unknown,_ as explained [here](https://github.com/yokoffing/Better-Fox/wiki/Ghostery#why-use-ghostery-over-ublock-origin).

Luckily, **Ghostery is an exception to the rule.** Ghostery's [anti-tracking technology](https://whotracks.me/blog/how_cliqz_antitracking_protects_users.html) is not based on blocklists and is able to remove unsafe datapoints (e.g. fingerprints, third-party cookies, unique identifiers, etc.) from requests without having to block them, drastically reducing breakage. You don't have to tinker with `about:config` either. That's always nice.

You can look at it this way: Where Betterfox does not alter the browser's behavior in order to prevent breakage, Ghostery will still remove unique identifiers associated with that behavior. (AFAIK, the only thing exception to this rule is referers, but I need to get with the team to validate this. This may boil down to a first-party vs. third-party tracking issue.)

***

> I can go over these options and help to merge them, but it may be best to wait until BetterFox's changes are finalized to avoid repetition/conflict of options.

Thanks for wanting to contribute! I've reviewed the Arkenfox / ghacks user.js many times, and I keep abreast of their [changelog](https://github.com/arkenfox/user.js/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Achangelog). So this shouldn't be necessary.

If there's something specifically you see there that could be beneficial in BetterFox, you can open an issue on [my repo](https://github.com/yokoffing/Better-Fox).

**Comment by 2br-2b** [comment]
In that case, I'll close the issue. Thanks for the in-depth response!

**Comment by Thorin-Oakenpants** [comment]
arkenfox moved to dFPI when it was stable enough - when FF96 came out: see here https://github.com/arkenfox/user.js/issues/1345 in Jan 2022 - because ANY earlier and isolation was compromised. Firefox itself did not roll it out to desktop until [much later](https://blog.mozilla.org/en/mozilla/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/) that year

I find the comment that betterfox used dFPI in March 2021 (as per the edit history) implausible - it wasn't even engineered at the time
